---
html_document:
    css: ../style.css
    theme: paper 
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Ongoing Projects 


- [Integrating Conflict Event Data](Projects/integration/integration_project.html) &mdash; Disaggregated studies of conflict typically rely on a single dataset to make inferences. In this project, we advocate for integrating multiple datasets to improve measurement and analysis.  
- [Tactical Adaptation](Projects/tactical_variation/tactical_variation_project.html) &mdash; This project examines why some violent non-state actors experiment with and develop a broad repertoire of tactics and targets to achieve their political aims while other groups consistently utilize the same methods across their lifespan.
- [Live Simultated Environments](Projects/eve_online/eve_online_project.html) &mdash; We leverage live simulated environments to examine individual and group-level normative and strategic behavior. 
- [Diplomatic Networks](Projects/diplomatic_networks/diplomatic_networks_project.html) &mdash; We explore structural breaks in diplomatic meeting networks as a predictor for shifts in foreign policy. 
<br>

### Working Papers

- <details><summary> "<a href="Projects/integration/dunford_et_al_2020.pdf" target="_blank">An Integrated Picture of Conflict</a>"</summary><blockquote>Growth in event datasets is fostering research about patterns, dynamics, causes, and consequences of conflict. Studies typically rely on a single dataset. Instead, we advocate integrating multiple datasets to improve measurement and analysis. We have generated an integrated dataset covering all violent events for Africa from 1997-2018 from three leading datasets (ACLED, UCDP-GED, and GTD). Our approach involves both pre-processing the data so that they are comparable and using an automated approach to produce an integrated dataset that is transparent and reproducible. Through examining these integrated data, we find substantial overlap across these three datasets. At the same time, each dataset includes events that conceptually should be captured in the other datasets, but are not. Thus, we view these integrated data as offering a better measure of violent conflict. A statistical analysis shows that geographic features frequently used in analyses of the location of conflict events --- including the distance from the capital or a border, terrain, economic development, and population--have different effects on the incidence and frequency of conflict events when using integrated data as compared to individual datasets. These illustrations highlight the potential for integration to advance conflict research by yielding a more complete and accurate picture of activity, which has repercussions for both descriptive and theoretical findings. Integration is likely to be increasingly worthwhile as event datasets proliferate, expand in coverage, and exhibit wider applications.</blockquote></details>


- <details><summary> "<a href="Projects/tactical_variation/dunford_2020.pdf" target="_blank">The Dark Side of Diversity: Membership Diversity and Tactical Innovation in Violent Non-state Organizations</a>" </summary><blockquote>Why do some violent non-state actors (NSA) regularly innovate while others do so rarely? Recent studies suggest variation in affiliation, bureaucratization, support, and competition yield different innovative capabilities. While emphasizing constraints, these studies tend to overlook the importance of internal drivers that make innovation more or less likely. I develop a theory of membership diversity in an NSA as an internal driver of innovation. Using panel data on 187 NSAs (1970 to 2018), I exploit variation in novel exposures to socially-relevant ethnic populations as a diversity treatment in an intent-to-treat design to estimate the relationship between membership composition and tactical innovation. I demonstrate the validity of the empirical strategy using a directed acyclic graph. The analysis finds that the diversity treatment increases both the likelihood and rate of tactical innovation. By treating membership composition as an information problem, the findings underscore the importance of knowing who is in an NSA when evaluating organizational capabilities. </blockquote></details>



- <details><summary> "<a href="" target="_blank">Gender Norms and Violent Behavior in a Virtual World</a>"</summary><blockquote>How does gender influence violent behavior? Existing research generally focuses on biological and contextual factors that drive variation in violence, often overlooking how internalized gender norms can influence violent actions. Isolating the effect of norms from biology is challenging because sex and gender are typically conﬂated. Moreover, it is difficult to observe and know if individuals behave the same publicly as opposed to privately. To get around these issues, we examine a novel multi-player computer game setting where players can operate characters of varying genders, thus holding biology constant. The data tracks more than 488,000 unique players from over 150 countries for their first 30 days of gameplay. By exploiting variation in game mechanics, we ﬁnd evidence that behavioral differences are attributable to internalized norms as opposed to biology or external sanctioning. We then leverage a natural experiment in the data to examine if these internalized norms can be altered. We find that both male and female players utilize their female characters more violently when exposed to examples of females in military roles. The project is the first to distinguish the effects of gender norms from the effects of biology or social sanctioning---conﬁrming the importance of gender norms while clarifying the differences these norms exert on men and women’s behavior.</blockquote></details>


- <details><summary> "<a href="Drafts/Dunford_and_Joseph_2018.pdf" target="_blank">Shifting foreign policies and punctuated diplomatic behavior</a>"</summary><blockquote>We develop a method to identify when states change their foreign policies based on an observable indicator: patterns of elite diplomatic meetings. We argue that elites choose diplomatic partners to advance a specific foreign policy agenda. When that agenda changes so do the incentives to choose diplomatic partners. To locate these breaks we apply non-parametric structural break tests to time series models that pre- dict a state’s diplomatic behavior. We argue that where these tests identify breaks in diplomatic behavior, a state has changed its foreign policy. We validate our theory using expert foreign policy analysis and quantitative cases. We first collect new daily diplomatic events data for Russia, Iran, the USA and Australia. We then com- pare structural breaks in these time series to expert assessments about foreign policy change. Consistent with expert reports, we locate structural breaks in Iran’s diplomatic behavior when Rouhani first comes to power, then in the months after sanctions are lifted; and in Russia’s diplomatic behavior 6 months before the Ukraine crisis, and then again when Russia extends its military into Syria. No break occurs in Australia’s or America’s diplomatic behavior as expected. We contribute to the empirical literature on conflict by providing new diplomatic data and a method to measure foreign pol- icy change, and to theories of diplomacy by linking aggregated patterns of diplomatic behavior to foreign policy choices—not underlying intentions.</blockquote></details>

<!-- - "<a href="" target="_blank">Measuring Tactical Variation within Violent Non-state Organizations</a>" -->

<br>
