---
html_document:
    css: ../style.css
    theme: paper 
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### Invited Talks

- **2020** "The Dark Side of Diversity: Membership Diversity and Tactical Innovation in Non-State Organizations", _Facebook_
- **2019** "Conflict Event History Data and Prediction", _Central Intelligence Agency_
- **2019** "Predicting Conflict Occurrence Using Search History Data", _Facebook_

### Conference Presentations

- **2020** "The Illusion of Precision", _International Studies Association_ (Canceled due to the COVID-19 outbreak)
- **2019** "Membership Diversity and Tactical Variation", _American Political Science Association_
- **2019** "Gender Norms and Violent Behavior in a Virtual World", _Politics and Computational Social Science_
- **2019** "Predicting Conflict Occurrence using Search History Data", _International Studies Association_
- **2018** "Advancing Measurement in the Study of Conflict and Political Violence", _Peace Science Society_
- **2017** "A Break from the Past: why mapping deviations in diplomatic networks reveals shifts in foreign policy strategies, _International Studies Association_ 
- **2017** "A Break from the Past: why mapping deviations in diplomatic networks reveals shifts in foreign policy strategies", _Peace Science Society_
- **2016** "An Automated Aggregation of Geo-coded Violent and Non-violent Conflict Events", _Peace Science Society_
- **2016** "Integrating African Conflict Event Data", _American Political Science Association_
- **2016** "MELTT: Matching Event Data by Location, Time, and Type", _The Society for Political Methodology_
- **2016** "MELTT: Matching Event Data by Location, Time, and Type", _Midwest Political Science Association_
- **2015** "Providing to Compete: An Examination of Social Welfare Provisions by Regime Change Movements", _Midwest Political Science Association_

### Workshops

- **2019** "Building a professional web presence using `R`". (Data Science in Action Seminar) _McCourt School of Public Policy, Georgetown University_
- **2018** "A Crash Course in Statistical Computing" (Short Course) _College of Behavioral and Social Sciences University of Maryland, College Park_
- **2017** "Applied Statistics and Data Management in `R`" (Short Course) _Smith School of Business, University of Maryland, College Park_
- **2017** "Tools and Best Practices for Integrating Spatial Data" (APSA Short Course co-taught with [Karsten Donnay](https://www.karstendonnay.net/) and [Andrew Linke](https://faculty.utah.edu/u6001910-Andrew_M._Linke/hm/index.hml)) _American Political Science Association_
- **2017** "An Introduction To Statistical Programing In `R`: A short course on processing, analyzing, and visualizing data in `R`" (Short Course) _Creative Associates International, Washington DC_
- **2017** "The ABC’s of Bayesian Estimation in `R`" (Talk) _University of Maryland, College Park_
- **2016** "Learning R Programming" (Short Course) _Department of Government and Politics, University of Maryland, College Park_
- **2016** "Web-scrapping and Automated Data Process in `R`" (Workshop) _University of Iceland, Reykjavik_
- **2016** "Web-scrapping and Automated Data Process in `R`" (Workshop) _University of Maryland, College Park_
- **2015** "Functional Programming in `R`" (Workshop) _University of Maryland, College Park_
- **2015** "Real-Time Modeling of Social Protest: Ferguson, Twitter, and the Opacity of Social Media Data" _University of Maryland, College Park_
