---
output: 
  html_document:
    css: ../style.css
    theme: paper 
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Overview

I primarily teach graduate-level computational social science courses at Georgetown University. As an instructor, I try to balance substance with methodological rigor by training students how to effectively employ computational methods to investigate, analyze, and learn from data to formulate and test theoretically-relevant hypotheses. In my instruction, I match formal computational training with hands-on empirical examples so that quantitative methods are taught in the context where they are applied. 

I aim to train students on how to: (i) utilize **_machine learning methods_** to explore and generate hypotheses from data; (ii) design and implement statistical designs geared toward effectively inferring **_causal relationships_** from observational and experimental data; (iii) **_synthesize_** disparate and unstructured data to draw meaningful insights from data related to public policy and political science inquiries; and (iv) **_visualize_** data to effectively communicate empirical findings. My goal is to train students to be effective consumers, critics, and producers of computational social science.

<hr>

### Course Catalog

<div style="margin-left: 2em;">

#### [Accelerated Statistics for Public Policy II (PPOL561)](http://ericdunford.com/ppol561/Syllabus/PPOL561-Accelerated-Statistics-for-Public-Policy-02.pdf)

Course taught: _Spring 2019, Spring 2020_

> This is the second course in the two-course sequence on quantitative methods for social science for the Masters of Science in Data Science for Public Policy (DSPP). The course builds on students’ understanding of multivariate regression and introduces advanced, but commonly used, methods of statistical analysis. The course is broadly divided into two part: advanced modeling and causal inference. Instruction will concentrate on how to determine the appropriate econometric approach in addressing various types of policy questions, while highlighting the challenges in isolating causal effects. The emphasis is on applied learning; formal proofs and mathematical rigor are presented but not the principal focus of the course. As part of our effort to teach effective communication skills, students will make presentations about applications using the techniques being studied in class.

#### [Data Science I: Foundations (PPOL564)](http://ericdunford.com/ppol564/syllabus/PPOL564-Syllabus.pdf)

Course taught: _Fall 2018, Fall 2019_

> This first course in the core data science sequence for the Masters of Science in Data Science for Public Policy (DSPP) introduces students to the programming and mathematical concepts that underpin statistical learning. The aim of the course is to provide DSPP students with the foundations necessary to grasp the concepts and algorithms encountered in Data Science II and III. Students will cover topics related to linear algebra (with a focus on linear regression and dimension reduction); multivariate calculus (with an emphasis on optimization algorithms, specifically gradient descent); and probability theory (with an emphasis on simulation and sampling). Throughout the course, students will be introduced to the fundamentals of programming and manipulating data in Python. Students will work in Jupyter notebooks and use Git/GitHub to submit coding assignments, developing literate programming and reproducible research skills they will use throughout the program.

#### [Introduction to Data Science (PPOL670)](http://ericdunford.com/ppol670/Syllabus/PPOL670-Introduction-to-DS_Syllabus.pdf)

Course taught: _Spring/Fall 2019, Spring 2020_

> This course teaches Masters of Public Policy (MPP) students how to synthesize disparate, possibly unstructured data in order to draw meaningful insights from data. Topics covered include fundamentals of functional programming in `R`, literate programming, data wrangling, data visualization, data extraction (via web scraping and APIs), text analysis, and machine learning methods. In addition, students will be exposed to Git and Github for reproducible research. The course aims to offer students a practical toolkit for data exploration. The objective of the course is to equip MPP students with the skills to incorporate data into their decision-making and analysis. 

</div>

<hr>

### Advising


I advise thesis projects for students in the [Masters of Conflict Resolution](https://government.georgetown.edu/conflict-resolution/) program at Georgetown University.

<div style="margin-left: 2em;">

#### Current Advisees

- Ayaka Oishi

</div>